kind: pipeline
name: build

platform:
  os: linux
  arch: arm64

steps:
  - name: debug
    image: alpine
    commands:
      - apk add --no-cache docker-cli
      - docker images
      - docker login repo.wheeler-network.com -u "$REPO_USER" -p "$REPO_PASS"
      - docker build --no-cache -t repo.wheeler-network.com/personal/backend .
      - docker push repo.wheeler-network.com/personal/backend

  - name: docker
    image: plugins/docker
    settings:
      repo: repo.wheeler-network.com/personal/backend
      registry: repo.wheeler-network.com
      username:
        from_secret: REPO_USER
      password:
        from_secret: REPO_PASS
      dockerfile: dockerfile
      use_cache: false
      auto_tag: true