kind: pipeline
name: build

platform:
  os: linux
  arch: arm64

steps:
  - name: infisical
    image: alpine
    environment:
      INF_HOST:
        from_secret: INF_HOST
      INF_CLIENT_ID:
        from_secret: INF_CLIENT_ID
      INF_CLIENT_SECRET:
        from_secret: INF_CLIENT_SECRET
      INF_PROJECT:
        from_secret: INF_PROJECT
    commands:
      - apk add --no-cache wget curl
      - wget https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.34.2/infisical_0.34.2_linux_arm64.tar.gz
      - tar -xvf infisical_0.34.2_linux_arm64.tar.gz
      - chmod +x infisical
      - mv infisical /usr/local/bin/infisical
      - export INFISICAL_TOKEN=$(infisical login --domain=$INF_HOST --method=universal-auth --client-id=$INF_CLIENT_ID --client-secret=$INF_CLIENT_SECRET --plain --silent)
      - echo $INFISICAL_TOKEN
      - curl -H "Authorization: Bearer $INFISICAL_TOKEN" "http://192.168.0.108:8080/api/v3/secrets/raw?environment=prod&workspaceId=$INF_PROJECT&secretPath=/keycloak" > .env
      # - infisical export --token=$INFISICAL_TOKEN --projectId=$INF_PROJECT --env=prod --format=dotenv > .env
      - cat .env

  - name: docker
    image: plugins/docker
    settings:
      repo: repo.wheeler-network.com/personal/backend
      registry: repo.wheeler-network.com
      username:
        from_secret: REPO_USER
      password:
        from_secret: REPO_PASS
      dockerfile: dockerfile
      use_cache: false
      auto_tag: true