kind: pipeline
name: build

platform:
  os: linux
  arch: arm64

steps:
  - name: infisical
    image: alpine
    commands:
      - apk add --no-cache wget
      - wget https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.34.2/infisical_0.34.2_linux_arm64.tar.gz
      - tar -xvf infisical_0.34.2_linux_arm64.tar.gz
      - chmod +x infisical
      - mv infisical /usr/local/bin/infisical
      - infisical login --domain $INF_URL --client-id $INF_CLIENT_ID --client-secret $INF_CLIENT_SECRET
      - infisical pull --env production --format dotenv > .env

  - name: docker
    image: plugins/docker
    settings:
      repo: repo.wheeler-network.com/personal/backend
      registry: repo.wheeler-network.com
      username:
        from_secret: REPO_USER
      password:
        from_secret: REPO_PASS
      dockerfile: dockerfile
      use_cache: false
      auto_tag: true