kind: pipeline
name: build

platform:
  os: linux
  arch: arm64

steps:
  - name: infisical
    image: alpine
    commands:
      - apk add --no-cache curl
      - curl -fsSL https://infisical.com/cli/install.sh | sh
      - infisical login --domain INF_URL --client-id INF_CLIENT_ID --client-secret INF_CLIENT_SECRET
      - infisical pull --env production --format dotenv > .env

  - name: docker
    image: plugins/docker
    settings:
      repo: repo.wheeler-network.com/personal/backend
      registry: repo.wheeler-network.com
      username:
        from_secret: REPO_USER
      password:
        from_secret: REPO_PASS
      dockerfile: dockerfile
      use_cache: false
      auto_tag: true