kind: pipeline
name: build

platform:
  os: linux
  arch: arm64

steps:
  - name: infisical
    image: alpine
    environment:
      INF_CLIENT_ID:
        from_secret: INF_CLIENT_ID
      INF_CLIENT_SECRET:
        from_secret: INF_CLIENT_SECRET
    commands:
      - apk add --no-cache wget
      - wget https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.34.2/infisical_0.34.2_linux_arm64.tar.gz
      - tar -xvf infisical_0.34.2_linux_arm64.tar.gz
      - chmod +x infisical
      - mv infisical /usr/local/bin/infisical
      - export INFISICAL_TOKEN=$(infisical login --domain=http://192.168.0.108:8080 --method=universal-auth --client-id=$INF_CLIENT_ID --client-secret=$INF_CLIENT_SECRET)
      - infisical export --env production --format dotenv > .env
      - cat .env

  - name: docker
    image: plugins/docker
    settings:
      repo: repo.wheeler-network.com/personal/backend
      registry: repo.wheeler-network.com
      username:
        from_secret: REPO_USER
      password:
        from_secret: REPO_PASS
      dockerfile: dockerfile
      use_cache: false
      auto_tag: true